# Generated by Django 3.2.8 on 2021-11-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='Group',
        ),
        migrations.AddField(
            model_name='client',
            name='Group',
            field=models.ManyToManyField(to='main.Group'),
        ),
    ]
