# Generated by Django 3.2.8 on 2021-11-04 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211104_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connecteddata',
            name='client',
        ),
        migrations.AddField(
            model_name='connecteddata',
            name='client',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.client'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='connecteddata',
            name='field',
        ),
        migrations.AddField(
            model_name='connecteddata',
            name='field',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.extrafields'),
        ),
    ]
