# Generated by Django 3.2.8 on 2021-11-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20211104_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrafields',
            name='field_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
