# Generated by Django 3.2.6 on 2021-12-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_extrafields_field_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={'verbose_name_plural': 'My API Keys'},
        ),
        migrations.AlterModelOptions(
            name='connecteddata',
            options={'verbose_name_plural': 'Connected Data Entries'},
        ),
        migrations.AlterModelOptions(
            name='extrafields',
            options={'verbose_name_plural': 'Extra Fields'},
        ),
        migrations.AlterField(
            model_name='connecteddata',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
